export const quizzes = [
  {
    _id: "1",
    quizName: "Mountain",
    quizImage: "/images/mountain.jpg",
    questions: [
      {
        questionNumber: 1,
        question:
          "Which of the following  mountain are formed due to the force generated by the endogenetic force, for example- when two plates collide head on, and their edges crumbled ?",
        options: [
          "Fold Mountains",
          "Block Mountains",
          "Volcanic Mountains",
          "Dissected mountains",
        ],
      },
      {
        questionNumber: 2,
        question: "What do you mean by world ‘Himalaya’ ?",
        options: [
          "Land of peaks",
          "Land of rising sun",
          "Adobe of snow",
          "Land of mountains",
        ],
      },
      {
        questionNumber: 3,
        question:
          "Do you know which mountain is thought to have the highest altitude ?",
        options: ["Cho Oyu", "Everest", "Fuji", "Denali"],
      },
      {
        questionNumber: 4,
        question:
          "According to the Guinness Book of World Records, where would you find the world’s oldest mountain range ?",
        options: ["Egypt", "South Africa", "Germany", "Nepal"],
      },
      {
        questionNumber: 5,
        question:
          "Which of the following mountain is called relict mountains ?",
        options: [
          "Himalayan Mountain",
          "Aravalli’s Mountain",
          "HIndu-Kush Mountain",
          "Nilgiris Mountain",
        ],
      },
    ],
    correctAnswers: ["a", "c", "b", "b", "d"],
  },
  {
    _id: "2",
    quizName: "Monuments",
    quizImage: "/images/monument.jpg",
    questions: [
      {
        questionNumber: 1,
        question:
          " Which building is known as “White Marble Mughal Architecture”?",
        options: ["Taj Mahal", "Khajurao", "Hampi", "Ajanta"],
      },
      {
        questionNumber: 2,
        question:
          "Which temples are well known for their Nagara style symbolism and erotic figures and sculptures?",
        options: ["Aksardham", "Khajuraho", "Hampi", "Ajanta"],
      },
      {
        questionNumber: 3,
        question:
          "Which caves are well known for their Indian-rock cut architecture?",
        options: ["Khajuraho", "Hampi", "Ajanta", "Ellora"],
      },
      {
        questionNumber: 4,
        question:
          " Which of the following is the oldest stone structures in India?",
        options: ["Taj", "Qutub minar", "Red ford", "Sanchi"],
      },
      {
        questionNumber: 5,
        question:
          "Which World Heritage Sites in India was built by Begum Bega?",
        options: ["Humayun’s Tomb", "Taj Mahal", "Red Ford", "Qutub Minar"],
      },
    ],
    correctAnswers: ["a", "b", "d", "d", "a"],
  },
  {
    _id: "3",
    quizName: "Museum",
    quizImage: "/images/museum.jpg",
    questions: [
      {
        questionNumber: 1,
        question:
          "The first Indian Satellite launched from Soviet Cosmodrome is ?",
        options: ["Bhaskara", "Bharat", "Rohini", "Aryabhatt"],
      },
      {
        questionNumber: 2,
        question:
          "The largest and the oldest museum of India is located in the state/union territory of ?",
        options: [
          "New Delhi",
          "West Bengal",
          "Arunachal Pradesh",
          "Uttar Pradesh",
        ],
      },
      {
        questionNumber: 3,
        question: "Largest Mint in India is located at ?",
        options: ["Mumbai", "Kolkata", "Hyderabad", "Nashik"],
      },
      {
        questionNumber: 4,
        question: "Shankar's International Dolls Museam is located at ?",
        options: ["Delhi", "Mumbai", "Kolkata", "Bhopal"],
      },
      {
        questionNumber: 5,
        question: "Prince of wales museam is located at ?",
        options: ["Jabalpur", "Banglore", "Mumbai", "Pune"],
      },
    ],
    correctAnswers: ["d", "b", "b", "a", "c"],
  },
  {
    _id: "4",
    quizName: "Animals",
    quizImage: "/images/animal.jpg",
    questions: [
      {
        questionNumber: 1,
        question: "Sloths often sleep while:",
        options: ["Standing up", "Pooping", "Hanging", "upside down"],
      },
      {
        questionNumber: 2,
        question:
          "Some animals, like red pandas, go into a deep sleep to conserve energy where their body temperature lowers and their respiration rate goes down. This deep sleep state is called:",
        options: ["Stagnation", "Torpor", "Reverie", "Halitosis"],
      },
      {
        questionNumber: 3,
        question:
          "Which one of the following is NOT a predator of the Brazilian tapir?",
        options: ["Pumas", "Capybaras", "Jaguars", "Anacondas"],
      },
      {
        questionNumber: 4,
        question:
          "Capybaras are specially adapted to a semi-aquatic lifestyle because?",
        options: [
          "They have a wide tail that acts as a flipper",
          "They have webbed feet",
          "They can hold their breath for up to 10 minutes",
          "They have gills",
        ],
      },
      {
        questionNumber: 5,
        question: "What special substance do mother koalas feed their young?",
        options: ["Mead", "Pap", "Keratin", "Pulp"],
      },
    ],
    correctAnswers: ["c", "b", "b", "b", "b"],
  },
];
